name: GitHub Actions
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          VERSION=$(npm version patch)
          git config user.name bot
          git config user.email bot@mail.com
          git add .
          git commit -m "bump $VERSION"
          git push