name: GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name bot
          git config user.email bot@mail.com
          git pull --ff-only
          npm version patch -m "bump version %s"
          git push